### PR TITLE
#35 removed all relative imports

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #35

### CODE REVIEW

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#64](https://github.com/ammaratef45/zold-flutter-client/issues/64) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#64` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#64](https://github.com/ammaratef45/zold-flutter-client/issues/64) is now out of scope

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#64](https://github.com/ammaratef45/zold-flutter-client/issues/64); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Pull request merged**
