### PR TITLE
Qr payment puzzles

### PR DESCRIPTION
**Pull request by ammaratef45**

### CODE REVIEW

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#36](https://github.com/ammaratef45/zold-flutter-client/issues/36) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#36` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#36](https://github.com/ammaratef45/zold-flutter-client/issues/36) is now out of scope

**Pull request merged**
