### PR TITLE
#31 created reusable dialogs

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #31 
 - Created Dialogs module.
 - Leaved a todo to continue replacement.

### CODE REVIEW

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#33](https://github.com/ammaratef45/zold-flutter-client/issues/33) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#33` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#33](https://github.com/ammaratef45/zold-flutter-client/issues/33) is now out of scope

**Pull request merged**
