### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #28, #29 and #30

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#32](https://github.com/ammaratef45/zold-flutter-client/issues/32) is now in scope, role is `REV`

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#32](https://github.com/ammaratef45/zold-flutter-client/issues/32); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#32` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#32](https://github.com/ammaratef45/zold-flutter-client/issues/32) is now out of scope

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/ammaratef45/zold-flutter-client/issues/32#issuecomment-473780627))

@ammaratef45 This is what I know about this job in [CGC59KB9B](https://www.0crat.com/p/CGC59KB9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#32](https://github.com/ammaratef45/zold-flutter-client/issues/32) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CGC59KB9B?q=%7Bjob%3A%27gh%3Aammaratef45%2Fzold-flutter-client%2332%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Pull request merged**
