### PR TITLE
#18 created the page to create QR images

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #18

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#23](https://github.com/ammaratef45/zold-flutter-client/issues/23) is now in scope, role is `REV`

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#23](https://github.com/ammaratef45/zold-flutter-client/issues/23); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#23` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#23](https://github.com/ammaratef45/zold-flutter-client/issues/23) is now out of scope

**Pull request merged**
