### PR TITLE
#49 take error message from job.json

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #49 
Added the error message from job.json when the job ends with an error.

### CODE REVIEW

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#63](https://github.com/ammaratef45/zold-flutter-client/issues/63) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#63` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#63](https://github.com/ammaratef45/zold-flutter-client/issues/63) is now out of scope

**Pull request merged**
