### PR TITLE
Adding VSC Configs - titles - buttons - debug mode no warning

### PR DESCRIPTION
**Pull request by amorenew**
For resolving issue 
Adding Visual Studio Configs #105
Adding page title #101 
Make default buttons styles #100 
Debug mode should not show warning page #107 

@ammaratef45  could you review it?
Thanks

### CODE REVIEW

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#106](https://github.com/ammaratef45/zold-flutter-client/issues/106) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#106](https://github.com/ammaratef45/zold-flutter-client/issues/106); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by ammaratef45** [comment]
@amorenew That was a really big PR, it took some time to review it.
Thanks for the help, everything is nice 👍

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#106` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#106](https://github.com/ammaratef45/zold-flutter-client/issues/106) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Pull request merged**
