### PR TITLE
texts modified

### PR DESCRIPTION
**Pull request by yegor256**
small modifications

### CODE REVIEW

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this pull request

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@yegor256 Thanks :+1:

**Comment by 0crat** [comment]
Job [#87](https://github.com/ammaratef45/zold-flutter-client/issues/87) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#87](https://github.com/ammaratef45/zold-flutter-client/issues/87); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#87` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#87](https://github.com/ammaratef45/zold-flutter-client/issues/87) is now out of scope

**Pull request merged**
