### PR TITLE
Get rid of texts inside the form fields #111

### PR DESCRIPTION
**Pull request by Nermeen78**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#116](https://github.com/ammaratef45/zold-flutter-client/issues/116) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#116](https://github.com/ammaratef45/zold-flutter-client/issues/116) is assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/4b69e069-77a9-46de-9c2d-7bba9bea49ae); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by amorenew** [comment]
I should not be responsible for merging pull requests only the Architect @ammaratef45 
So

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/ammaratef45/zold-flutter-client/issues/116#issuecomment-500083841); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by amorenew** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/116#issuecomment-500083929))

@amorenew The user @amorenew[/z](https://www.0crat.com/u/amorenew) resigned from [#116](https://github.com/ammaratef45/zold-flutter-client/issues/116), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
This pull request [#116](https://github.com/ammaratef45/zold-flutter-client/issues/116) is assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/480f8479-2f20-45e6-b472-bbf76ec2605f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@amorenew You're supposed to give a regular code review
check [27](https://www.zerocracy.com/policy.html#27) and [55](https://www.zerocracy.com/policy.html#55) in the policy

**Comment by amorenew** [comment]
@Nermeen78 Hello,
Could you resolve the Conflicting files?
Thanks

**Comment by Nermeen78** [comment]
@0crat wait for mreging

**Comment by 0crat** [comment]
> @0crat wait for mreging  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/116#issuecomment-501450287))

@Nermeen78 It's a code review job [#116](https://github.com/ammaratef45/zold-flutter-client/issues/116), can't put it on hold

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@Nermeen78 only the ticket itself can be put on wait

**Review by amorenew — APPROVED** [review]

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#116](https://github.com/ammaratef45/zold-flutter-client/issues/116) is now out of scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@172b6e24-c076-4e67-b31d-0a5185ba3ff6, thread: pool-5-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [c4bfac0b-191e-4a22-8b04-2079a3341d1f](https://www.0crat.com/footprint/CGC59KB9B/c4bfac0b-191e-4a22-8b04-2079a3341d1f), Type: "Transfer shares"

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by sereshqua** [comment]
@Nermeen78 please make sure, that a pull request description explains the solution proposed and contains a link to the original ticket it is related to 

@amorenew please make sure: 1) you will find at least 3 issues during next code review - you did not mention any issues here 2) start a comment ([see](https://github.com/ammaratef45/zold-flutter-client/pull/116#issuecomment-500083841)) with the user name it is addressed to

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/ammaratef45/zold-flutter-client/issues/116#issuecomment-501873400))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@172b6e24-c076-4e67-b31d-0a5185ba3ff6, thread: pool-5-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [3143e865-e8ad-4f10-9303-68a0512f7d84](https://www.0crat.com/footprint/CGC59KB9B/3143e865-e8ad-4f10-9303-68a0512f7d84), Type: "Transfer shares"

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
