### PR TITLE
Feature login validate

### PR DESCRIPTION
**Pull request by amorenew**
Changes:
1-Added login validation message
2-Added on tab hide keyboard for login
Related issue #108

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#114](https://github.com/ammaratef45/zold-flutter-client/issues/114) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#114](https://github.com/ammaratef45/zold-flutter-client/issues/114); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
This pull request [#114](https://github.com/ammaratef45/zold-flutter-client/issues/114) is assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78), here is [why](https://www.0crat.com/footprint/CGC59KB9B/9bed97fd-a2cb-4b67-82b0-32fe6194ced5); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@nermeen78[/z](https://www.0crat.com/u/nermeen78) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Review by ammaratef45 — APPROVED** [review]
@amorenew That was great

**Comment by 0crat** [comment]
Job [#114](https://github.com/ammaratef45/zold-flutter-client/issues/114) is not in the agenda of @nermeen78[/z](https://www.0crat.com/u/nermeen78), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @nermeen78[/z](https://www.0crat.com/u/nermeen78), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#114](https://github.com/ammaratef45/zold-flutter-client/issues/114) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by sereshqua** [comment]
@0crat quality bad

@Nermeen78 Nermeen did not do the any job but he is assigned to it

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
